apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgresql
    tier: database
spec:
  selector:
    matchLabels:
      app: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
        tier: database
    spec:
      containers:
        - name: postgres
          image: postgres:14-alpine
          env:
          - name: POSTGRES_DB
            value: controlevendas
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: "1234567"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
              name: postgresql
            
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pvc
  

---
kind: Service
apiVersion: v1
metadata:
  name: postgresql
  labels:
    app: postgresql
    tier: database
spec:
  selector:
    app: postgresql
    tier: database
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP