apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  template:
    metadata:
      name: my-job-pod
    spec:
      containers:
      - name: my-container-busybox
        image: busybox
        command: 
        - "bin/sh"
        - "-c"
        - "for i in 1 2; do echo Lucky number $i = $((1 + RAMDOM % 70)); done"
      restartPolicy: Never
