apiVersion: v1
kind: Pod
metadata:
  name: resources-pod
  labels:
    name: resources-pod
spec:
  containers:
  - name: apache-container
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
